name: payu_core
description: Flutter package with Payu core functionality and models.
version: 1.0.3
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  payu_interface:
    git:
      url: https://github.com/DariuszPiechota/PayU-Flutter-Old.git
      path: payu_interface
      ref: latest-tag
  url_launcher: ^6.1.6
dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^4.1.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
